### ISSUE TITLE
Missing request body passes validation

### ISSUE THREAD

**Issue by sisp** [grktsh/falcon-oas#2]
Hi,

First of all, thanks for this very promising OpenAPI middleware for Falcon!

I've noticed that a missing/empty request body, i.e. no JSON object at all, passes request body validation although the OpenAPI spec has a schema with required fields. When setting an invalid request body, e.g. an empty JSON object `{}`, validation fails and returns "Unmarshal Error" (400) as expected.

**Comment by sisp** [comment]
Nevermind, I wasn't aware that I have to set the `required` flag to `true` under `requestBody`. I'm closing the issue as there's in fact on problem.

**Comment by grktsh** [comment]
NP.  Feel free to file issues!
