### ISSUE TITLE
Changelog and frequent releases

### ISSUE THREAD

**Issue by sisp** [grktsh/falcon-oas#28]
Are you open to maintaining a changelog, which I think is helpful especially with `0.y.z` library versions to keep track of compatible vs. breaking changes.

Somewhat related to this, are you open to more frequent releases, so changes become available shortly afterwards?

The same applies to `python-oas`.

I've also contributed to [`mobx-keystone`](https://github.com/xaviergonz/mobx-keystone), which is a relatively young but nicely progressing project. I came to appreciate the changelog and frequent releases there and take it as inspiration elsewhere. What do you think?

**Comment by grktsh** [comment]
It may be a radical idea, I don't understand a need for the changelog file. [Releases](https://github.com/grktsh/falcon-oas/releases) page is enough for me.

I'm open to more frequent releases.  I'll release next versions at least within this week.

**Comment by sisp** [comment]
> Releases page is enough for me.

Good point, `mobx-keystone` is not using GitHub releases.

> I'm open to more frequent releases. I'll release next versions at least within this week.

Great, much appreciated! :blush:

**Comment by grktsh** [comment]
Done!
- https://github.com/grktsh/python-oas/releases/tag/v0.2.0
- https://github.com/grktsh/falcon-oas/releases/tag/v0.5.0

**Comment by sisp** [comment]
Thank you very much!
